[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
